### ISSUE TITLE
Caching doesn't work with Yarn v2

### ISSUE THREAD

**Issue by tylerbutler** [microsoft/lage#129] opened 2021-02-18 23:55 UTC
I've been testing lage with Yarn 2 in the [microsoft/FluidFramework](https://github.com/microsoft/FluidFramework) monorepo, and from what I can tell, lage doesn't seem to cache properly.

I don't have a _minimal_ repro, but you can repro using my `y2` branch here: https://github.com/tylerbutler/FluidFramework/tree/y2

To repro:

1. Clone my FluidFramework fork and switch to the `y2` branch.
2. Install yarn globally using `npm i -g yarn`.
3. Run `yarn install`.
4. Run `yarn run lage l-build`.

The build will run and likely fail. Once complete run the same build command again; it will re-run everything as if nothing is cached.

**Comment by vignanl** [comment] 2021-03-30 13:38
Root cause for this issue is, lage has a dependency on workspace-tools which parses yarn lock files, currently it can only parse yarn version 1 lock files but breaks for lock files of yarn version 2.

Opened issue in workspace-tools repo. #https://github.com/microsoft/workspace-tools/issues/36, resolving this issue should fix caching issue.

**Closed** 2023-02-15 16:43 UTC
